name: PR Reminder
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  update-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: SeongHo5/pr-reminder@v1.2
        with:
          platform: 'slack'
          webhook-url: 'https://hooks.slack.com/services/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'
          remind-time: 1
