name: Sync OpenAPI YAML to API Docs

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - develop
    paths:
      - 'docs/api/**/*.yaml'

jobs:
  synchronize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Trigger API Docs Sync via Octokit
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.request('POST /repos/SeongHo5/pages-test/dispatches', {
              owner: 'SeongHo5',
              repo: 'pages-test',
              event_type: 'sync-api-docs',
              client_payload: {
                unit: false,
                integration: true
              },
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });

