name: Sync OpenAPI YAML to API Docs

on:
  workflow_dispatch:

jobs:
  synchronize:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Trigger API Docs Sync via Octokit
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.request('POST /repos/SeongHo5/pages-test/dispatches', {
              event_type: 'sync-api-docs',
              client_payload: {
                unit: false,
                integration: true
              },
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });

