name: LOCAT CD

on:

  workflow_run:
    workflows:
      - "LOCAT CI"
    types:
      - completed

jobs:
  locat-CD:
    if: github.event.workflow_run.conclusion == 'success' && contains(github.ref, 'main')
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO }}/prod:latest
            ${{ secrets.DOCKER_REPO }}/prod:${{ github.sha }}

#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        id: deploy-prod
#        with:
#          host: ${{ secrets.HOST_PROD }}
#          username: ubuntu
#          key: ${{ secrets.KEY_PROD }}
#          envs: GITHUB_SHA
#          script: |
#            sudo docker rm -f locat-server || true
#            sudo docker pull ${{ secrets.DOCKER_REPO }}/prod:latest
#            sudo docker run -d \
#              --name locat-server \
#              --env-file .env \
#              -p 80:80 \
#              ${{ secrets.DOCKER_REPO }}/prod:latest
#            docker image prune -f
